gem 'buildr-iidea', :version => '0.0.7'
require 'buildr_iidea'

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))
require 'buildr_ipojo'

repositories.remote << Buildr::Ipojo.remote_repository

desc 'CLI INterface to Pojoizer'
define('buildr.ipojo.cli') do
  project.version = '1.0'
  project.group = 'buildr.ipojo'
  compile.options.source = '1.6'
  compile.options.target = '1.6'
  compile.options.lint = 'all'
  project.no_ipr
  compile.with Buildr::Ipojo.requires
  package(:jar, :file => _("../lib/buildr/ipojo/ipojo_cli.jar"))
end
